vim.filetype.add({ extension = { templ = "templ" } })
vim.filetype.add({ extension = { hurl = "hurl" } })
vim.filetype.add({ extension = { re = "reason" } })
vim.filetype.add({ extension = { purs = "purescript" } })
vim.filetype.add({ filename = { ["tsconfig.json"] = "json" } })
